# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The portable international postal address. Maps to
  # [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/wi
  # ki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls: the
  # autocomplete
  # attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-cont
  # rols-the-autocomplete-attribute).
  class Address < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The first line of the address, such as number and street, for example,
    # `173 Drury Lane`. Needed for data entry, and Compliance and Risk checks.
    # This field needs to pass the full address.
    # @return [String]
    attr_accessor :address_line_1

    # The second line of the address, for example, a suite or apartment number.
    # @return [String]
    attr_accessor :address_line_2

    # A city, town, or village. Smaller than `admin_area_level_1`.
    # @return [String]
    attr_accessor :admin_area_2

    # The highest-level sub-division in a country, which is usually a province,
    # state, or ISO-3166-2 subdivision. This data is formatted for postal
    # delivery, for example, `CA` and not `California`. Value, by country,
    # is:<ul><li>UK. A county.</li><li>US. A state.</li><li>Canada. A
    # province.</li><li>Japan. A prefecture.</li><li>Switzerland. A
    # *kanton*.</li></ul>
    # @return [String]
    attr_accessor :admin_area_1

    # The postal code, which is the ZIP code or equivalent. Typically required
    # for countries with a postal code or an equivalent. See [postal
    # code](https://en.wikipedia.org/wiki/Postal_code).
    # @return [String]
    attr_accessor :postal_code

    # The [2-character ISO 3166-1 code](/api/rest/reference/country-codes/) that
    # identifies the country or region.<blockquote><strong>Note:</strong> The
    # country code for Great Britain is <code>GB</code> and not <code>UK</code>
    # as used in the top-level domain names for that country. Use the `C2`
    # country code for China worldwide for comparable uncontrolled price (CUP)
    # method, bank card, and cross-border transactions.</blockquote>
    # @return [String]
    attr_accessor :country_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['address_line_1'] = 'address_line_1'
      @_hash['address_line_2'] = 'address_line_2'
      @_hash['admin_area_2'] = 'admin_area_2'
      @_hash['admin_area_1'] = 'admin_area_1'
      @_hash['postal_code'] = 'postal_code'
      @_hash['country_code'] = 'country_code'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        address_line_1
        address_line_2
        admin_area_2
        admin_area_1
        postal_code
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(country_code:, address_line_1: SKIP, address_line_2: SKIP,
                   admin_area_2: SKIP, admin_area_1: SKIP, postal_code: SKIP)
      @address_line_1 = address_line_1 unless address_line_1 == SKIP
      @address_line_2 = address_line_2 unless address_line_2 == SKIP
      @admin_area_2 = admin_area_2 unless admin_area_2 == SKIP
      @admin_area_1 = admin_area_1 unless admin_area_1 == SKIP
      @postal_code = postal_code unless postal_code == SKIP
      @country_code = country_code
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      country_code = hash.key?('country_code') ? hash['country_code'] : nil
      address_line_1 =
        hash.key?('address_line_1') ? hash['address_line_1'] : SKIP
      address_line_2 =
        hash.key?('address_line_2') ? hash['address_line_2'] : SKIP
      admin_area_2 = hash.key?('admin_area_2') ? hash['admin_area_2'] : SKIP
      admin_area_1 = hash.key?('admin_area_1') ? hash['admin_area_1'] : SKIP
      postal_code = hash.key?('postal_code') ? hash['postal_code'] : SKIP

      # Create object from extracted values.
      Address.new(country_code: country_code,
                  address_line_1: address_line_1,
                  address_line_2: address_line_2,
                  admin_area_2: admin_area_2,
                  admin_area_1: admin_area_1,
                  postal_code: postal_code)
    end
  end
end
