# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Indicates the type of payment data passed, in case of Non China the payment
  # data is 3DSECURE and for China it is EMV.
  class ApplePayPaymentDataType
    APPLE_PAY_PAYMENT_DATA_TYPE = [
      # TODO: Write general description for ENUM_3DSECURE
      ENUM_3DSECURE = '3DSECURE'.freeze,

      # TODO: Write general description for EMV
      EMV = 'EMV'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
