# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Additional attributes associated with apple pay.
  class ApplePayAttributes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The details about a customer in PayPal's system of record.
    # @return [CustomerInformation]
    attr_accessor :customer

    # Base vaulting specification. The object can be extended for specific use
    # cases within each payment_source that supports vaulting.
    # @return [VaultInstruction]
    attr_accessor :vault

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['customer'] = 'customer'
      @_hash['vault'] = 'vault'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        customer
        vault
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(customer: SKIP, vault: SKIP)
      @customer = customer unless customer == SKIP
      @vault = vault unless vault == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      customer = CustomerInformation.from_hash(hash['customer']) if hash['customer']
      vault = VaultInstruction.from_hash(hash['vault']) if hash['vault']

      # Create object from extracted values.
      ApplePayAttributes.new(customer: customer,
                             vault: vault)
    end
  end
end
