# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Information about cardholder possession validation and cardholder
  # identification and verifications (ID&V).
  class AssuranceDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # If true, indicates that Cardholder possession validation has been
    # performed on returned payment credential.
    # @return [TrueClass | FalseClass]
    attr_accessor :account_verified

    # If true, indicates that identification and verifications (ID&V) was
    # performed on the returned payment credential.If false, the same risk-based
    # authentication can be performed as you would for card transactions. This
    # risk-based authentication can include, but not limited to, step-up with 3D
    # Secure protocol if applicable.
    # @return [TrueClass | FalseClass]
    attr_accessor :card_holder_authenticated

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_verified'] = 'account_verified'
      @_hash['card_holder_authenticated'] = 'card_holder_authenticated'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_verified
        card_holder_authenticated
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_verified: false, card_holder_authenticated: false)
      @account_verified = account_verified unless account_verified == SKIP
      unless card_holder_authenticated == SKIP
        @card_holder_authenticated =
          card_holder_authenticated
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_verified = hash['account_verified'] ||= false
      card_holder_authenticated = hash['card_holder_authenticated'] ||= false

      # Create object from extracted values.
      AssuranceDetails.new(account_verified: account_verified,
                           card_holder_authenticated: card_holder_authenticated)
    end
  end
end
