# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The status for the authorized payment.
  class AuthorizationStatus
    AUTHORIZATION_STATUS = [
      # TODO: Write general description for CREATED
      CREATED = 'CREATED'.freeze,

      # TODO: Write general description for CAPTURED
      CAPTURED = 'CAPTURED'.freeze,

      # TODO: Write general description for DENIED
      DENIED = 'DENIED'.freeze,

      # TODO: Write general description for PARTIALLY_CAPTURED
      PARTIALLY_CAPTURED = 'PARTIALLY_CAPTURED'.freeze,

      # TODO: Write general description for VOIDED
      VOIDED = 'VOIDED'.freeze,

      # TODO: Write general description for PENDING
      PENDING = 'PENDING'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
