# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Information used to pay using BLIK one-click flow.
  class BlikOneClickPaymentObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The merchant generated, unique reference serving as a primary identifier
    # for accounts connected between Blik and a merchant.
    # @return [String]
    attr_accessor :consumer_reference

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['consumer_reference'] = 'consumer_reference'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        consumer_reference
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(consumer_reference: SKIP)
      @consumer_reference = consumer_reference unless consumer_reference == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      consumer_reference =
        hash.key?('consumer_reference') ? hash['consumer_reference'] : SKIP

      # Create object from extracted values.
      BlikOneClickPaymentObject.new(consumer_reference: consumer_reference)
    end
  end
end
