# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The status and status details of a captured payment.
  class CaptureStatusWithDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The status of the captured payment.
    # @return [CaptureStatus]
    attr_accessor :status

    # The details of the captured payment status.
    # @return [CaptureStatusDetails]
    attr_accessor :status_details

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['status'] = 'status'
      @_hash['status_details'] = 'status_details'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        status
        status_details
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(status: SKIP, status_details: SKIP)
      @status = status unless status == SKIP
      @status_details = status_details unless status_details == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash.key?('status') ? hash['status'] : SKIP
      status_details = CaptureStatusDetails.from_hash(hash['status_details']) if
        hash['status_details']

      # Create object from extracted values.
      CaptureStatusWithDetails.new(status: status,
                                   status_details: status_details)
    end
  end
end
