# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The reason why the captured payment status is `PENDING` or `DENIED`.
  class CaptureIncompleteReason
    CAPTURE_INCOMPLETE_REASON = [
      # TODO: Write general description for BUYER_COMPLAINT
      BUYER_COMPLAINT = 'BUYER_COMPLAINT'.freeze,

      # TODO: Write general description for CHARGEBACK
      CHARGEBACK = 'CHARGEBACK'.freeze,

      # TODO: Write general description for ECHECK
      ECHECK = 'ECHECK'.freeze,

      # TODO: Write general description for INTERNATIONAL_WITHDRAWAL
      INTERNATIONAL_WITHDRAWAL = 'INTERNATIONAL_WITHDRAWAL'.freeze,

      # TODO: Write general description for OTHER
      OTHER = 'OTHER'.freeze,

      # TODO: Write general description for PENDING_REVIEW
      PENDING_REVIEW = 'PENDING_REVIEW'.freeze,

      # TODO: Write general description for
      # RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION
      RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION = 'RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION'.freeze,

      # TODO: Write general description for REFUNDED
      REFUNDED = 'REFUNDED'.freeze,

      # TODO: Write general description for
      # TRANSACTION_APPROVED_AWAITING_FUNDING
      TRANSACTION_APPROVED_AWAITING_FUNDING = 'TRANSACTION_APPROVED_AWAITING_FUNDING'.freeze,

      # TODO: Write general description for UNILATERAL
      UNILATERAL = 'UNILATERAL'.freeze,

      # TODO: Write general description for VERIFICATION_REQUIRED
      VERIFICATION_REQUIRED = 'VERIFICATION_REQUIRED'.freeze,

      # TODO: Write general description for DECLINED_BY_RISK_FRAUD_FILTERS
      DECLINED_BY_RISK_FRAUD_FILTERS = 'DECLINED_BY_RISK_FRAUD_FILTERS'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
