# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The card network or brand. Applies to credit, debit, gift, and payment
  # cards.
  class CardBrand
    CARD_BRAND = [
      # TODO: Write general description for VISA
      VISA = 'VISA'.freeze,

      # TODO: Write general description for MASTERCARD
      MASTERCARD = 'MASTERCARD'.freeze,

      # TODO: Write general description for DISCOVER
      DISCOVER = 'DISCOVER'.freeze,

      # TODO: Write general description for AMEX
      AMEX = 'AMEX'.freeze,

      # TODO: Write general description for SOLO
      SOLO = 'SOLO'.freeze,

      # TODO: Write general description for JCB
      JCB = 'JCB'.freeze,

      # TODO: Write general description for STAR
      STAR = 'STAR'.freeze,

      # TODO: Write general description for DELTA
      DELTA = 'DELTA'.freeze,

      # TODO: Write general description for SWITCH
      SWITCH = 'SWITCH'.freeze,

      # TODO: Write general description for MAESTRO
      MAESTRO = 'MAESTRO'.freeze,

      # TODO: Write general description for CB_NATIONALE
      CB_NATIONALE = 'CB_NATIONALE'.freeze,

      # TODO: Write general description for CONFIGOGA
      CONFIGOGA = 'CONFIGOGA'.freeze,

      # TODO: Write general description for CONFIDIS
      CONFIDIS = 'CONFIDIS'.freeze,

      # TODO: Write general description for ELECTRON
      ELECTRON = 'ELECTRON'.freeze,

      # TODO: Write general description for CETELEM
      CETELEM = 'CETELEM'.freeze,

      # TODO: Write general description for CHINA_UNION_PAY
      CHINA_UNION_PAY = 'CHINA_UNION_PAY'.freeze,

      # TODO: Write general description for DINERS
      DINERS = 'DINERS'.freeze,

      # TODO: Write general description for ELO
      ELO = 'ELO'.freeze,

      # TODO: Write general description for HIPER
      HIPER = 'HIPER'.freeze,

      # TODO: Write general description for HIPERCARD
      HIPERCARD = 'HIPERCARD'.freeze,

      # TODO: Write general description for RUPAY
      RUPAY = 'RUPAY'.freeze,

      # TODO: Write general description for GE
      GE = 'GE'.freeze,

      # TODO: Write general description for SYNCHRONY
      SYNCHRONY = 'SYNCHRONY'.freeze,

      # TODO: Write general description for EFTPOS
      EFTPOS = 'EFTPOS'.freeze,

      # TODO: Write general description for UNKNOWN
      UNKNOWN = 'UNKNOWN'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
