# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Additional attributes associated with the use of this card.
  class CardAttributesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The details about a saved Card payment source.
    # @return [CardVaultResponse]
    attr_accessor :vault

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['vault'] = 'vault'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        vault
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(vault: SKIP)
      @vault = vault unless vault == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      vault = CardVaultResponse.from_hash(hash['vault']) if hash['vault']

      # Create object from extracted values.
      CardAttributesResponse.new(vault: vault)
    end
  end
end
