# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Additional attributes associated with the use of this card.
  class CardAttributes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The details about a customer in PayPal's system of record.
    # @return [CardCustomerInformation]
    attr_accessor :customer

    # Basic vault instruction specification that can be extended by specific
    # payment sources that supports vaulting.
    # @return [VaultInstructionBase]
    attr_accessor :vault

    # The API caller can opt in to verify the card through PayPal offered
    # verification services (e.g. Smart Dollar Auth, 3DS).
    # @return [CardVerification]
    attr_accessor :verification

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['customer'] = 'customer'
      @_hash['vault'] = 'vault'
      @_hash['verification'] = 'verification'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        customer
        vault
        verification
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(customer: SKIP, vault: SKIP, verification: SKIP)
      @customer = customer unless customer == SKIP
      @vault = vault unless vault == SKIP
      @verification = verification unless verification == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      customer = CardCustomerInformation.from_hash(hash['customer']) if hash['customer']
      vault = VaultInstructionBase.from_hash(hash['vault']) if hash['vault']
      verification = CardVerification.from_hash(hash['verification']) if hash['verification']

      # Create object from extracted values.
      CardAttributes.new(customer: customer,
                         vault: vault,
                         verification: verification)
    end
  end
end
