# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The condition that is covered for the transaction.
  class DisputeCategory
    DISPUTE_CATEGORY = [
      # TODO: Write general description for ITEM_NOT_RECEIVED
      ITEM_NOT_RECEIVED = 'ITEM_NOT_RECEIVED'.freeze,

      # TODO: Write general description for UNAUTHORIZED_TRANSACTION
      UNAUTHORIZED_TRANSACTION = 'UNAUTHORIZED_TRANSACTION'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
