# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Information used to pay using eps.
  class EPSPaymentObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The full name representation like Mr J Smith.
    # @return [String]
    attr_accessor :name

    # The [two-character ISO 3166-1 code](/api/rest/reference/country-codes/)
    # that identifies the country or region.<blockquote><strong>Note:</strong>
    # The country code for Great Britain is <code>GB</code> and not
    # <code>UK</code> as used in the top-level domain names for that country.
    # Use the `C2` country code for China worldwide for comparable uncontrolled
    # price (CUP) method, bank card, and cross-border transactions.</blockquote>
    # @return [String]
    attr_accessor :country_code

    # The business identification code (BIC). In payments systems, a BIC is used
    # to identify a specific business, most commonly a bank.
    # @return [String]
    attr_accessor :bic

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['country_code'] = 'country_code'
      @_hash['bic'] = 'bic'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        country_code
        bic
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name: SKIP, country_code: SKIP, bic: SKIP)
      @name = name unless name == SKIP
      @country_code = country_code unless country_code == SKIP
      @bic = bic unless bic == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      country_code = hash.key?('country_code') ? hash['country_code'] : SKIP
      bic = hash.key?('bic') ? hash['bic'] : SKIP

      # Create object from extracted values.
      EPSPaymentObject.new(name: name,
                           country_code: country_code,
                           bic: bic)
    end
  end
end
