# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # A classification for the method of purchase fulfillment (e.g shipping,
  # in-store pickup, etc). Either `type` or `options` may be present, but not
  # both.
  class FulfillmentType
    FULFILLMENT_TYPE = [
      # TODO: Write general description for SHIPPING
      SHIPPING = 'SHIPPING'.freeze,

      # TODO: Write general description for PICKUP_IN_PERSON
      PICKUP_IN_PERSON = 'PICKUP_IN_PERSON'.freeze,

      # TODO: Write general description for PICKUP_IN_STORE
      PICKUP_IN_STORE = 'PICKUP_IN_STORE'.freeze,

      # TODO: Write general description for PICKUP_FROM_PERSON
      PICKUP_FROM_PERSON = 'PICKUP_FROM_PERSON'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
