# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The payment card to use to fund a Google Pay payment response. Can be a
  # credit or debit card.
  class GooglePayCardResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The card holder's name as it appears on the card.
    # @return [String]
    attr_accessor :name

    # The last digits of the payment card.
    # @return [String]
    attr_accessor :last_digits

    # Type of card. i.e Credit, Debit and so on.
    # @return [CardType]
    attr_accessor :type

    # The card network or brand. Applies to credit, debit, gift, and payment
    # cards.
    # @return [CardBrand]
    attr_accessor :brand

    # The portable international postal address. Maps to
    # [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/
    # wiki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls:
    # the autocomplete
    # attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-co
    # ntrols-the-autocomplete-attribute).
    # @return [Address]
    attr_accessor :billing_address

    # Results of Authentication such as 3D Secure.
    # @return [AuthenticationResponse]
    attr_accessor :authentication_result

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['last_digits'] = 'last_digits'
      @_hash['type'] = 'type'
      @_hash['brand'] = 'brand'
      @_hash['billing_address'] = 'billing_address'
      @_hash['authentication_result'] = 'authentication_result'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        last_digits
        type
        brand
        billing_address
        authentication_result
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name: SKIP, last_digits: SKIP, type: SKIP, brand: SKIP,
                   billing_address: SKIP, authentication_result: SKIP)
      @name = name unless name == SKIP
      @last_digits = last_digits unless last_digits == SKIP
      @type = type unless type == SKIP
      @brand = brand unless brand == SKIP
      @billing_address = billing_address unless billing_address == SKIP
      @authentication_result = authentication_result unless authentication_result == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      last_digits = hash.key?('last_digits') ? hash['last_digits'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      brand = hash.key?('brand') ? hash['brand'] : SKIP
      billing_address = Address.from_hash(hash['billing_address']) if hash['billing_address']
      authentication_result = AuthenticationResponse.from_hash(hash['authentication_result']) if
        hash['authentication_result']

      # Create object from extracted values.
      GooglePayCardResponse.new(name: name,
                                last_digits: last_digits,
                                type: type,
                                brand: brand,
                                billing_address: billing_address,
                                authentication_result: authentication_result)
    end
  end
end
