# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Additional attributes associated with the use of this card.
  class GooglePayCardAttributes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The API caller can opt in to verify the card through PayPal offered
    # verification services (e.g. Smart Dollar Auth, 3DS).
    # @return [CardVerification]
    attr_accessor :verification

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['verification'] = 'verification'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        verification
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(verification: SKIP)
      @verification = verification unless verification == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      verification = CardVerification.from_hash(hash['verification']) if hash['verification']

      # Create object from extracted values.
      GooglePayCardAttributes.new(verification: verification)
    end
  end
end
