# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Authentication Method which is used for the card transaction.
  class GooglePayAuthenticationMethod
    GOOGLE_PAY_AUTHENTICATION_METHOD = [
      # TODO: Write general description for PAN_ONLY
      PAN_ONLY = 'PAN_ONLY'.freeze,

      # TODO: Write general description for CRYPTOGRAM_3DS
      CRYPTOGRAM_3DS = 'CRYPTOGRAM_3DS'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
