# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The item category type.
  class ItemCategory
    ITEM_CATEGORY = [
      # TODO: Write general description for DIGITAL_GOODS
      DIGITAL_GOODS = 'DIGITAL_GOODS'.freeze,

      # TODO: Write general description for PHYSICAL_GOODS
      PHYSICAL_GOODS = 'PHYSICAL_GOODS'.freeze,

      # TODO: Write general description for DONATION
      DONATION = 'DONATION'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
