# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Liability shift indicator. The outcome of the issuer's authentication.
  class LiabilityShiftIndicator
    LIABILITY_SHIFT_INDICATOR = [
      # TODO: Write general description for NO
      NO = 'NO'.freeze,

      # TODO: Write general description for POSSIBLE
      POSSIBLE = 'POSSIBLE'.freeze,

      # TODO: Write general description for UNKNOWN
      UNKNOWN = 'UNKNOWN'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
