# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The name of the party.
  class Name < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # When the party is a person, the party's given, or first, name.
    # @return [String]
    attr_accessor :given_name

    # When the party is a person, the party's surname or family name. Also known
    # as the last name. Required when the party is a person. Use also to store
    # multiple surnames including the matronymic, or mother's, surname.
    # @return [String]
    attr_accessor :surname

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['given_name'] = 'given_name'
      @_hash['surname'] = 'surname'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        given_name
        surname
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(given_name: SKIP, surname: SKIP)
      @given_name = given_name unless given_name == SKIP
      @surname = surname unless surname == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      given_name = hash.key?('given_name') ? hash['given_name'] : SKIP
      surname = hash.key?('surname') ? hash['surname'] : SKIP

      # Create object from extracted values.
      Name.new(given_name: given_name,
               surname: surname)
    end
  end
end
