# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Reference values used by the card network to identify a transaction.
  class NetworkTransactionReference < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Transaction reference id returned by the scheme. For Visa and Amex, this
    # is the "Tran id" field in response. For MasterCard, this is the "BankNet
    # reference id" field in response. For Discover, this is the "NRID" field in
    # response. The pattern we expect for this field from Visa/Amex/CB/Discover
    # is numeric, Mastercard/BNPP is alphanumeric and Paysecure is alphanumeric
    # with special character -.
    # @return [String]
    attr_accessor :id

    # The date that the transaction was authorized by the scheme. This field may
    # not be returned for all networks. MasterCard refers to this field as
    # "BankNet reference date.
    # @return [String]
    attr_accessor :date

    # The card network or brand. Applies to credit, debit, gift, and payment
    # cards.
    # @return [CardBrand]
    attr_accessor :network

    # Reference ID issued for the card transaction. This ID can be used to track
    # the transaction across processors, card brands and issuing banks.
    # @return [String]
    attr_accessor :acquirer_reference_number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['date'] = 'date'
      @_hash['network'] = 'network'
      @_hash['acquirer_reference_number'] = 'acquirer_reference_number'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        date
        network
        acquirer_reference_number
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id:, date: SKIP, network: SKIP,
                   acquirer_reference_number: SKIP)
      @id = id
      @date = date unless date == SKIP
      @network = network unless network == SKIP
      unless acquirer_reference_number == SKIP
        @acquirer_reference_number =
          acquirer_reference_number
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : nil
      date = hash.key?('date') ? hash['date'] : SKIP
      network = hash.key?('network') ? hash['network'] : SKIP
      acquirer_reference_number =
        hash.key?('acquirer_reference_number') ? hash['acquirer_reference_number'] : SKIP

      # Create object from extracted values.
      NetworkTransactionReference.new(id: id,
                                      date: date,
                                      network: network,
                                      acquirer_reference_number: acquirer_reference_number)
    end
  end
end
