# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The order status.
  class OrderStatus
    ORDER_STATUS = [
      # TODO: Write general description for CREATED
      CREATED = 'CREATED'.freeze,

      # TODO: Write general description for SAVED
      SAVED = 'SAVED'.freeze,

      # TODO: Write general description for APPROVED
      APPROVED = 'APPROVED'.freeze,

      # TODO: Write general description for VOIDED
      VOIDED = 'VOIDED'.freeze,

      # TODO: Write general description for COMPLETED
      COMPLETED = 'COMPLETED'.freeze,

      # TODO: Write general description for PAYER_ACTION_REQUIRED
      PAYER_ACTION_REQUIRED = 'PAYER_ACTION_REQUIRED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
