# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # DEPRECATED. Configures a <strong>Continue</strong> or <strong>Pay
  # Now</strong> checkout flow.  The fields in `application_context` are now
  # available in the `experience_context` object under the `payment_source`
  # which supports them (eg.
  # `payment_source.paypal.experience_context.user_action`). Please specify this
  # field in the `experience_context` object instead of the
  # `application_context` object.
  class OrderApplicationContextUserAction
    ORDER_APPLICATION_CONTEXT_USER_ACTION = [
      # TODO: Write general description for CONTINUE
      CONTINUE = 'CONTINUE'.freeze,

      # TODO: Write general description for PAY_NOW
      PAY_NOW = 'PAY_NOW'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
