# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Transactions status result identifier. The outcome of the issuer's
  # authentication.
  class PAResStatus
    PA_RES_STATUS = [
      # TODO: Write general description for Y
      Y = 'Y'.freeze,

      # TODO: Write general description for N
      N = 'N'.freeze,

      # TODO: Write general description for U
      U = 'U'.freeze,

      # TODO: Write general description for A
      A = 'A'.freeze,

      # TODO: Write general description for C
      C = 'C'.freeze,

      # TODO: Write general description for R
      R = 'R'.freeze,

      # TODO: Write general description for D
      D = 'D'.freeze,

      # TODO: Write general description for I
      I = 'I'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
