# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The merchant-preferred payment methods.
  class PayeePaymentMethodPreference
    PAYEE_PAYMENT_METHOD_PREFERENCE = [
      # TODO: Write general description for UNRESTRICTED
      UNRESTRICTED = 'UNRESTRICTED'.freeze,

      # TODO: Write general description for IMMEDIATE_PAYMENT_REQUIRED
      IMMEDIATE_PAYMENT_REQUIRED = 'IMMEDIATE_PAYMENT_REQUIRED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
