# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The person or party who initiated or triggered the payment.
  class PaymentInitiator
    PAYMENT_INITIATOR = [
      # TODO: Write general description for CUSTOMER
      CUSTOMER = 'CUSTOMER'.freeze,

      # TODO: Write general description for MERCHANT
      MERCHANT = 'MERCHANT'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
