# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Any additional payment instructions to be consider during payment
  # processing. This processing instruction is applicable for Capturing an order
  # or Authorizing an Order.
  class PaymentInstruction < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # An array of various fees, commissions, tips, or donations. This field is
    # only applicable to merchants that been enabled for PayPal Complete
    # Payments Platform for Marketplaces and Platforms capability.
    # @return [Array[PlatformFee]]
    attr_accessor :platform_fees

    # The funds that are held on behalf of the merchant.
    # @return [DisbursementMode]
    attr_accessor :disbursement_mode

    # This field is only enabled for selected merchants/partners to use and
    # provides the ability to trigger a specific pricing rate/plan for a payment
    # transaction. The list of eligible 'payee_pricing_tier_id' would be
    # provided to you by your Account Manager. Specifying values other than the
    # one provided to you by your account manager would result in an error.
    # @return [String]
    attr_accessor :payee_pricing_tier_id

    # FX identifier generated returned by PayPal to be used for payment
    # processing in order to honor FX rate (for eligible integrations) to be
    # used when amount is settled/received into the payee account.
    # @return [String]
    attr_accessor :payee_receivable_fx_rate_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['platform_fees'] = 'platform_fees'
      @_hash['disbursement_mode'] = 'disbursement_mode'
      @_hash['payee_pricing_tier_id'] = 'payee_pricing_tier_id'
      @_hash['payee_receivable_fx_rate_id'] = 'payee_receivable_fx_rate_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        platform_fees
        disbursement_mode
        payee_pricing_tier_id
        payee_receivable_fx_rate_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(platform_fees: SKIP,
                   disbursement_mode: DisbursementMode::INSTANT,
                   payee_pricing_tier_id: SKIP,
                   payee_receivable_fx_rate_id: SKIP)
      @platform_fees = platform_fees unless platform_fees == SKIP
      @disbursement_mode = disbursement_mode unless disbursement_mode == SKIP
      @payee_pricing_tier_id = payee_pricing_tier_id unless payee_pricing_tier_id == SKIP
      unless payee_receivable_fx_rate_id == SKIP
        @payee_receivable_fx_rate_id =
          payee_receivable_fx_rate_id
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      platform_fees = nil
      unless hash['platform_fees'].nil?
        platform_fees = []
        hash['platform_fees'].each do |structure|
          platform_fees << (PlatformFee.from_hash(structure) if structure)
        end
      end

      platform_fees = SKIP unless hash.key?('platform_fees')
      disbursement_mode =
        hash['disbursement_mode'] ||= DisbursementMode::INSTANT
      payee_pricing_tier_id =
        hash.key?('payee_pricing_tier_id') ? hash['payee_pricing_tier_id'] : SKIP
      payee_receivable_fx_rate_id =
        hash.key?('payee_receivable_fx_rate_id') ? hash['payee_receivable_fx_rate_id'] : SKIP

      # Create object from extracted values.
      PaymentInstruction.new(platform_fees: platform_fees,
                             disbursement_mode: disbursement_mode,
                             payee_pricing_tier_id: payee_pricing_tier_id,
                             payee_receivable_fx_rate_id: payee_receivable_fx_rate_id)
    end
  end
end
