# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The declined payment transactions might have payment advice codes. The card
  # networks, like Visa and Mastercard, return payment advice codes.
  class PaymentAdviceCode
    PAYMENT_ADVICE_CODE = [
      # TODO: Write general description for ENUM_01
      ENUM_01 = '01'.freeze,

      # TODO: Write general description for ENUM_02
      ENUM_02 = '02'.freeze,

      # TODO: Write general description for ENUM_03
      ENUM_03 = '03'.freeze,

      # TODO: Write general description for ENUM_21
      ENUM_21 = '21'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
