# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The payment source definition.
  class PaymentSource < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The payment card to use to fund a payment. Can be a credit or debit
    # card.<blockquote><strong>Note:</strong> Passing card number, cvv and
    # expiry directly via the API requires <a
    # href="https://www.pcisecuritystandards.org/pci_security/completing_self_as
    # sessment"> PCI SAQ D compliance</a>. <br>*PayPal offers a mechanism by
    # which you do not have to take on the <strong>PCI SAQ D</strong> burden by
    # using hosted fields - refer to <a
    # href="https://developer.paypal.com/docs/checkout/advanced/integrate/">this
    # Integration Guide</a>*.</blockquote>
    # @return [CardRequest]
    attr_accessor :card

    # The tokenized payment source to fund a payment.
    # @return [Token]
    attr_accessor :token

    # A resource that identifies a PayPal Wallet is used for payment.
    # @return [PaypalWallet]
    attr_accessor :paypal

    # Information needed to pay using Bancontact.
    # @return [BancontactPaymentRequest]
    attr_accessor :bancontact

    # Information needed to pay using BLIK.
    # @return [BlikPaymentRequest]
    attr_accessor :blik

    # Information needed to pay using eps.
    # @return [EpsPaymentRequest]
    attr_accessor :eps

    # Information needed to pay using giropay.
    # @return [GiropayPaymentRequest]
    attr_accessor :giropay

    # Information needed to pay using iDEAL.
    # @return [IdealPaymentRequest]
    attr_accessor :ideal

    # Information needed to pay using MyBank.
    # @return [MybankPaymentRequest]
    attr_accessor :mybank

    # Information needed to pay using P24 (Przelewy24).
    # @return [P24PaymentRequest]
    attr_accessor :p24

    # Information needed to pay using Sofort.
    # @return [SofortPaymentRequest]
    attr_accessor :sofort

    # Information needed to pay using Trustly.
    # @return [TrustlyPaymentRequest]
    attr_accessor :trustly

    # Information needed to pay using ApplePay.
    # @return [ApplePayRequest]
    attr_accessor :apple_pay

    # Information needed to pay using Google Pay.
    # @return [GooglePayRequest]
    attr_accessor :google_pay

    # Information needed to pay using Venmo.
    # @return [VenmoWalletRequest]
    attr_accessor :venmo

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card'] = 'card'
      @_hash['token'] = 'token'
      @_hash['paypal'] = 'paypal'
      @_hash['bancontact'] = 'bancontact'
      @_hash['blik'] = 'blik'
      @_hash['eps'] = 'eps'
      @_hash['giropay'] = 'giropay'
      @_hash['ideal'] = 'ideal'
      @_hash['mybank'] = 'mybank'
      @_hash['p24'] = 'p24'
      @_hash['sofort'] = 'sofort'
      @_hash['trustly'] = 'trustly'
      @_hash['apple_pay'] = 'apple_pay'
      @_hash['google_pay'] = 'google_pay'
      @_hash['venmo'] = 'venmo'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        card
        token
        paypal
        bancontact
        blik
        eps
        giropay
        ideal
        mybank
        p24
        sofort
        trustly
        apple_pay
        google_pay
        venmo
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(card: SKIP, token: SKIP, paypal: SKIP, bancontact: SKIP,
                   blik: SKIP, eps: SKIP, giropay: SKIP, ideal: SKIP,
                   mybank: SKIP, p24: SKIP, sofort: SKIP, trustly: SKIP,
                   apple_pay: SKIP, google_pay: SKIP, venmo: SKIP)
      @card = card unless card == SKIP
      @token = token unless token == SKIP
      @paypal = paypal unless paypal == SKIP
      @bancontact = bancontact unless bancontact == SKIP
      @blik = blik unless blik == SKIP
      @eps = eps unless eps == SKIP
      @giropay = giropay unless giropay == SKIP
      @ideal = ideal unless ideal == SKIP
      @mybank = mybank unless mybank == SKIP
      @p24 = p24 unless p24 == SKIP
      @sofort = sofort unless sofort == SKIP
      @trustly = trustly unless trustly == SKIP
      @apple_pay = apple_pay unless apple_pay == SKIP
      @google_pay = google_pay unless google_pay == SKIP
      @venmo = venmo unless venmo == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card = CardRequest.from_hash(hash['card']) if hash['card']
      token = Token.from_hash(hash['token']) if hash['token']
      paypal = PaypalWallet.from_hash(hash['paypal']) if hash['paypal']
      bancontact = BancontactPaymentRequest.from_hash(hash['bancontact']) if hash['bancontact']
      blik = BlikPaymentRequest.from_hash(hash['blik']) if hash['blik']
      eps = EpsPaymentRequest.from_hash(hash['eps']) if hash['eps']
      giropay = GiropayPaymentRequest.from_hash(hash['giropay']) if hash['giropay']
      ideal = IdealPaymentRequest.from_hash(hash['ideal']) if hash['ideal']
      mybank = MybankPaymentRequest.from_hash(hash['mybank']) if hash['mybank']
      p24 = P24PaymentRequest.from_hash(hash['p24']) if hash['p24']
      sofort = SofortPaymentRequest.from_hash(hash['sofort']) if hash['sofort']
      trustly = TrustlyPaymentRequest.from_hash(hash['trustly']) if hash['trustly']
      apple_pay = ApplePayRequest.from_hash(hash['apple_pay']) if hash['apple_pay']
      google_pay = GooglePayRequest.from_hash(hash['google_pay']) if hash['google_pay']
      venmo = VenmoWalletRequest.from_hash(hash['venmo']) if hash['venmo']

      # Create object from extracted values.
      PaymentSource.new(card: card,
                        token: token,
                        paypal: paypal,
                        bancontact: bancontact,
                        blik: blik,
                        eps: eps,
                        giropay: giropay,
                        ideal: ideal,
                        mybank: mybank,
                        p24: p24,
                        sofort: sofort,
                        trustly: trustly,
                        apple_pay: apple_pay,
                        google_pay: google_pay,
                        venmo: venmo)
    end
  end
end
