# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # A Resource representing a request to vault a Card.
  class PaymentTokenRequestCard < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The card holder's name as it appears on the card.
    # @return [String]
    attr_accessor :name

    # The primary account number (PAN) for the payment card.
    # @return [String]
    attr_accessor :number

    # The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date
    # and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
    # @return [String]
    attr_accessor :expiry

    # The three- or four-digit security code of the card. Also known as the CVV,
    # CVC, CVN, CVE, or CID. This parameter cannot be present in the request
    # when `payment_initiator=MERCHANT`.
    # @return [String]
    attr_accessor :security_code

    # The card network or brand. Applies to credit, debit, gift, and payment
    # cards.
    # @return [CardBrand]
    attr_accessor :brand

    # The portable international postal address. Maps to
    # [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/
    # wiki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls:
    # the autocomplete
    # attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-co
    # ntrols-the-autocomplete-attribute).
    # @return [Address]
    attr_accessor :billing_address

    # The portable international postal address. Maps to
    # [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/
    # wiki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls:
    # the autocomplete
    # attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-co
    # ntrols-the-autocomplete-attribute).
    # @return [Object]
    attr_accessor :network_transaction_reference

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['number'] = 'number'
      @_hash['expiry'] = 'expiry'
      @_hash['security_code'] = 'security_code'
      @_hash['brand'] = 'brand'
      @_hash['billing_address'] = 'billing_address'
      @_hash['network_transaction_reference'] =
        'network_transaction_reference'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        number
        expiry
        security_code
        brand
        billing_address
        network_transaction_reference
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name: SKIP, number: SKIP, expiry: SKIP, security_code: SKIP,
                   brand: SKIP, billing_address: SKIP,
                   network_transaction_reference: SKIP)
      @name = name unless name == SKIP
      @number = number unless number == SKIP
      @expiry = expiry unless expiry == SKIP
      @security_code = security_code unless security_code == SKIP
      @brand = brand unless brand == SKIP
      @billing_address = billing_address unless billing_address == SKIP
      unless network_transaction_reference == SKIP
        @network_transaction_reference =
          network_transaction_reference
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      number = hash.key?('number') ? hash['number'] : SKIP
      expiry = hash.key?('expiry') ? hash['expiry'] : SKIP
      security_code = hash.key?('security_code') ? hash['security_code'] : SKIP
      brand = hash.key?('brand') ? hash['brand'] : SKIP
      billing_address = Address.from_hash(hash['billing_address']) if hash['billing_address']
      network_transaction_reference =
        hash.key?('network_transaction_reference') ? hash['network_transaction_reference'] : SKIP

      # Create object from extracted values.
      PaymentTokenRequestCard.new(name: name,
                                  number: number,
                                  expiry: expiry,
                                  security_code: security_code,
                                  brand: brand,
                                  billing_address: billing_address,
                                  network_transaction_reference: network_transaction_reference)
    end
  end
end
