# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The type of landing page to show on the PayPal site for customer checkout.
  class PaypalExperienceLandingPage
    PAYPAL_EXPERIENCE_LANDING_PAGE = [
      # TODO: Write general description for LOGIN
      LOGIN = 'LOGIN'.freeze,

      # TODO: Write general description for GUEST_CHECKOUT
      GUEST_CHECKOUT = 'GUEST_CHECKOUT'.freeze,

      # TODO: Write general description for NO_PREFERENCE
      NO_PREFERENCE = 'NO_PREFERENCE'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
