# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The account status indicates whether the buyer has verified the financial
  # details associated with their PayPal account.
  class PaypalWalletAccountVerificationStatus
    PAYPAL_WALLET_ACCOUNT_VERIFICATION_STATUS = [
      # TODO: Write general description for VERIFIED
      VERIFIED = 'VERIFIED'.freeze,

      # TODO: Write general description for UNVERIFIED
      UNVERIFIED = 'UNVERIFIED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
