# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Processor response code for the non-PayPal payment processor errors.
  class ProcessorResponseCode
    PROCESSOR_RESPONSE_CODE = [
      # TODO: Write general description for ENUM_0000
      ENUM_0000 = '0000'.freeze,

      # TODO: Write general description for ENUM_00N7
      ENUM_00N7 = '00N7'.freeze,

      # TODO: Write general description for ENUM_0100
      ENUM_0100 = '0100'.freeze,

      # TODO: Write general description for ENUM_0390
      ENUM_0390 = '0390'.freeze,

      # TODO: Write general description for ENUM_0500
      ENUM_0500 = '0500'.freeze,

      # TODO: Write general description for ENUM_0580
      ENUM_0580 = '0580'.freeze,

      # TODO: Write general description for ENUM_0800
      ENUM_0800 = '0800'.freeze,

      # TODO: Write general description for ENUM_0880
      ENUM_0880 = '0880'.freeze,

      # TODO: Write general description for ENUM_0890
      ENUM_0890 = '0890'.freeze,

      # TODO: Write general description for ENUM_0960
      ENUM_0960 = '0960'.freeze,

      # TODO: Write general description for ENUM_0R00
      ENUM_0R00 = '0R00'.freeze,

      # TODO: Write general description for ENUM_1000
      ENUM_1000 = '1000'.freeze,

      # TODO: Write general description for ENUM_10BR
      ENUM_10BR = '10BR'.freeze,

      # TODO: Write general description for ENUM_1300
      ENUM_1300 = '1300'.freeze,

      # TODO: Write general description for ENUM_1310
      ENUM_1310 = '1310'.freeze,

      # TODO: Write general description for ENUM_1312
      ENUM_1312 = '1312'.freeze,

      # TODO: Write general description for ENUM_1317
      ENUM_1317 = '1317'.freeze,

      # TODO: Write general description for ENUM_1320
      ENUM_1320 = '1320'.freeze,

      # TODO: Write general description for ENUM_1330
      ENUM_1330 = '1330'.freeze,

      # TODO: Write general description for ENUM_1335
      ENUM_1335 = '1335'.freeze,

      # TODO: Write general description for ENUM_1340
      ENUM_1340 = '1340'.freeze,

      # TODO: Write general description for ENUM_1350
      ENUM_1350 = '1350'.freeze,

      # TODO: Write general description for ENUM_1352
      ENUM_1352 = '1352'.freeze,

      # TODO: Write general description for ENUM_1360
      ENUM_1360 = '1360'.freeze,

      # TODO: Write general description for ENUM_1370
      ENUM_1370 = '1370'.freeze,

      # TODO: Write general description for ENUM_1380
      ENUM_1380 = '1380'.freeze,

      # TODO: Write general description for ENUM_1382
      ENUM_1382 = '1382'.freeze,

      # TODO: Write general description for ENUM_1384
      ENUM_1384 = '1384'.freeze,

      # TODO: Write general description for ENUM_1390
      ENUM_1390 = '1390'.freeze,

      # TODO: Write general description for ENUM_1393
      ENUM_1393 = '1393'.freeze,

      # TODO: Write general description for ENUM_5100
      ENUM_5100 = '5100'.freeze,

      # TODO: Write general description for ENUM_5110
      ENUM_5110 = '5110'.freeze,

      # TODO: Write general description for ENUM_5120
      ENUM_5120 = '5120'.freeze,

      # TODO: Write general description for ENUM_5130
      ENUM_5130 = '5130'.freeze,

      # TODO: Write general description for ENUM_5135
      ENUM_5135 = '5135'.freeze,

      # TODO: Write general description for ENUM_5140
      ENUM_5140 = '5140'.freeze,

      # TODO: Write general description for ENUM_5150
      ENUM_5150 = '5150'.freeze,

      # TODO: Write general description for ENUM_5160
      ENUM_5160 = '5160'.freeze,

      # TODO: Write general description for ENUM_5170
      ENUM_5170 = '5170'.freeze,

      # TODO: Write general description for ENUM_5180
      ENUM_5180 = '5180'.freeze,

      # TODO: Write general description for ENUM_5190
      ENUM_5190 = '5190'.freeze,

      # TODO: Write general description for ENUM_5200
      ENUM_5200 = '5200'.freeze,

      # TODO: Write general description for ENUM_5210
      ENUM_5210 = '5210'.freeze,

      # TODO: Write general description for ENUM_5400
      ENUM_5400 = '5400'.freeze,

      # TODO: Write general description for ENUM_5500
      ENUM_5500 = '5500'.freeze,

      # TODO: Write general description for ENUM_5650
      ENUM_5650 = '5650'.freeze,

      # TODO: Write general description for ENUM_5700
      ENUM_5700 = '5700'.freeze,

      # TODO: Write general description for ENUM_5710
      ENUM_5710 = '5710'.freeze,

      # TODO: Write general description for ENUM_5800
      ENUM_5800 = '5800'.freeze,

      # TODO: Write general description for ENUM_5900
      ENUM_5900 = '5900'.freeze,

      # TODO: Write general description for ENUM_5910
      ENUM_5910 = '5910'.freeze,

      # TODO: Write general description for ENUM_5920
      ENUM_5920 = '5920'.freeze,

      # TODO: Write general description for ENUM_5930
      ENUM_5930 = '5930'.freeze,

      # TODO: Write general description for ENUM_5950
      ENUM_5950 = '5950'.freeze,

      # TODO: Write general description for ENUM_6300
      ENUM_6300 = '6300'.freeze,

      # TODO: Write general description for ENUM_7600
      ENUM_7600 = '7600'.freeze,

      # TODO: Write general description for ENUM_7700
      ENUM_7700 = '7700'.freeze,

      # TODO: Write general description for ENUM_7710
      ENUM_7710 = '7710'.freeze,

      # TODO: Write general description for ENUM_7800
      ENUM_7800 = '7800'.freeze,

      # TODO: Write general description for ENUM_7900
      ENUM_7900 = '7900'.freeze,

      # TODO: Write general description for ENUM_8000
      ENUM_8000 = '8000'.freeze,

      # TODO: Write general description for ENUM_8010
      ENUM_8010 = '8010'.freeze,

      # TODO: Write general description for ENUM_8020
      ENUM_8020 = '8020'.freeze,

      # TODO: Write general description for ENUM_8030
      ENUM_8030 = '8030'.freeze,

      # TODO: Write general description for ENUM_8100
      ENUM_8100 = '8100'.freeze,

      # TODO: Write general description for ENUM_8110
      ENUM_8110 = '8110'.freeze,

      # TODO: Write general description for ENUM_8220
      ENUM_8220 = '8220'.freeze,

      # TODO: Write general description for ENUM_9100
      ENUM_9100 = '9100'.freeze,

      # TODO: Write general description for ENUM_9500
      ENUM_9500 = '9500'.freeze,

      # TODO: Write general description for ENUM_9510
      ENUM_9510 = '9510'.freeze,

      # TODO: Write general description for ENUM_9520
      ENUM_9520 = '9520'.freeze,

      # TODO: Write general description for ENUM_9530
      ENUM_9530 = '9530'.freeze,

      # TODO: Write general description for ENUM_9540
      ENUM_9540 = '9540'.freeze,

      # TODO: Write general description for ENUM_9600
      ENUM_9600 = '9600'.freeze,

      # TODO: Write general description for PCNR
      PCNR = 'PCNR'.freeze,

      # TODO: Write general description for PCVV
      PCVV = 'PCVV'.freeze,

      # TODO: Write general description for PP06
      PP06 = 'PP06'.freeze,

      # TODO: Write general description for PPRN
      PPRN = 'PPRN'.freeze,

      # TODO: Write general description for PPAD
      PPAD = 'PPAD'.freeze,

      # TODO: Write general description for PPAB
      PPAB = 'PPAB'.freeze,

      # TODO: Write general description for PPAE
      PPAE = 'PPAE'.freeze,

      # TODO: Write general description for PPAG
      PPAG = 'PPAG'.freeze,

      # TODO: Write general description for PPAI
      PPAI = 'PPAI'.freeze,

      # TODO: Write general description for PPAR
      PPAR = 'PPAR'.freeze,

      # TODO: Write general description for PPAU
      PPAU = 'PPAU'.freeze,

      # TODO: Write general description for PPAV
      PPAV = 'PPAV'.freeze,

      # TODO: Write general description for PPAX
      PPAX = 'PPAX'.freeze,

      # TODO: Write general description for PPBG
      PPBG = 'PPBG'.freeze,

      # TODO: Write general description for PPC2
      PPC2 = 'PPC2'.freeze,

      # TODO: Write general description for PPCE
      PPCE = 'PPCE'.freeze,

      # TODO: Write general description for PPCO
      PPCO = 'PPCO'.freeze,

      # TODO: Write general description for PPCR
      PPCR = 'PPCR'.freeze,

      # TODO: Write general description for PPCT
      PPCT = 'PPCT'.freeze,

      # TODO: Write general description for PPCU
      PPCU = 'PPCU'.freeze,

      # TODO: Write general description for PPD3
      PPD3 = 'PPD3'.freeze,

      # TODO: Write general description for PPDC
      PPDC = 'PPDC'.freeze,

      # TODO: Write general description for PPDI
      PPDI = 'PPDI'.freeze,

      # TODO: Write general description for PPDV
      PPDV = 'PPDV'.freeze,

      # TODO: Write general description for PPDT
      PPDT = 'PPDT'.freeze,

      # TODO: Write general description for PPEF
      PPEF = 'PPEF'.freeze,

      # TODO: Write general description for PPEL
      PPEL = 'PPEL'.freeze,

      # TODO: Write general description for PPER
      PPER = 'PPER'.freeze,

      # TODO: Write general description for PPEX
      PPEX = 'PPEX'.freeze,

      # TODO: Write general description for PPFE
      PPFE = 'PPFE'.freeze,

      # TODO: Write general description for PPFI
      PPFI = 'PPFI'.freeze,

      # TODO: Write general description for PPFR
      PPFR = 'PPFR'.freeze,

      # TODO: Write general description for PPFV
      PPFV = 'PPFV'.freeze,

      # TODO: Write general description for PPGR
      PPGR = 'PPGR'.freeze,

      # TODO: Write general description for PPH1
      PPH1 = 'PPH1'.freeze,

      # TODO: Write general description for PPIF
      PPIF = 'PPIF'.freeze,

      # TODO: Write general description for PPII
      PPII = 'PPII'.freeze,

      # TODO: Write general description for PPIM
      PPIM = 'PPIM'.freeze,

      # TODO: Write general description for PPIT
      PPIT = 'PPIT'.freeze,

      # TODO: Write general description for PPLR
      PPLR = 'PPLR'.freeze,

      # TODO: Write general description for PPLS
      PPLS = 'PPLS'.freeze,

      # TODO: Write general description for PPMB
      PPMB = 'PPMB'.freeze,

      # TODO: Write general description for PPMC
      PPMC = 'PPMC'.freeze,

      # TODO: Write general description for PPMD
      PPMD = 'PPMD'.freeze,

      # TODO: Write general description for PPNC
      PPNC = 'PPNC'.freeze,

      # TODO: Write general description for PPNL
      PPNL = 'PPNL'.freeze,

      # TODO: Write general description for PPNM
      PPNM = 'PPNM'.freeze,

      # TODO: Write general description for PPNT
      PPNT = 'PPNT'.freeze,

      # TODO: Write general description for PPPH
      PPPH = 'PPPH'.freeze,

      # TODO: Write general description for PPPI
      PPPI = 'PPPI'.freeze,

      # TODO: Write general description for PPPM
      PPPM = 'PPPM'.freeze,

      # TODO: Write general description for PPQC
      PPQC = 'PPQC'.freeze,

      # TODO: Write general description for PPRE
      PPRE = 'PPRE'.freeze,

      # TODO: Write general description for PPRF
      PPRF = 'PPRF'.freeze,

      # TODO: Write general description for PPRR
      PPRR = 'PPRR'.freeze,

      # TODO: Write general description for PPS0
      PPS0 = 'PPS0'.freeze,

      # TODO: Write general description for PPS1
      PPS1 = 'PPS1'.freeze,

      # TODO: Write general description for PPS2
      PPS2 = 'PPS2'.freeze,

      # TODO: Write general description for PPS3
      PPS3 = 'PPS3'.freeze,

      # TODO: Write general description for PPS4
      PPS4 = 'PPS4'.freeze,

      # TODO: Write general description for PPS5
      PPS5 = 'PPS5'.freeze,

      # TODO: Write general description for PPS6
      PPS6 = 'PPS6'.freeze,

      # TODO: Write general description for PPSC
      PPSC = 'PPSC'.freeze,

      # TODO: Write general description for PPSD
      PPSD = 'PPSD'.freeze,

      # TODO: Write general description for PPSE
      PPSE = 'PPSE'.freeze,

      # TODO: Write general description for PPTE
      PPTE = 'PPTE'.freeze,

      # TODO: Write general description for PPTF
      PPTF = 'PPTF'.freeze,

      # TODO: Write general description for PPTI
      PPTI = 'PPTI'.freeze,

      # TODO: Write general description for PPTR
      PPTR = 'PPTR'.freeze,

      # TODO: Write general description for PPTT
      PPTT = 'PPTT'.freeze,

      # TODO: Write general description for PPTV
      PPTV = 'PPTV'.freeze,

      # TODO: Write general description for PPUA
      PPUA = 'PPUA'.freeze,

      # TODO: Write general description for PPUC
      PPUC = 'PPUC'.freeze,

      # TODO: Write general description for PPUE
      PPUE = 'PPUE'.freeze,

      # TODO: Write general description for PPUI
      PPUI = 'PPUI'.freeze,

      # TODO: Write general description for PPUP
      PPUP = 'PPUP'.freeze,

      # TODO: Write general description for PPUR
      PPUR = 'PPUR'.freeze,

      # TODO: Write general description for PPVC
      PPVC = 'PPVC'.freeze,

      # TODO: Write general description for PPVE
      PPVE = 'PPVE'.freeze,

      # TODO: Write general description for PPVT
      PPVT = 'PPVT'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
