# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The instruction to process an order.
  class ProcessingInstruction
    PROCESSING_INSTRUCTION = [
      # TODO: Write general description for ORDER_COMPLETE_ON_PAYMENT_APPROVAL
      ORDER_COMPLETE_ON_PAYMENT_APPROVAL = 'ORDER_COMPLETE_ON_PAYMENT_APPROVAL'.freeze,

      # TODO: Write general description for NO_INSTRUCTION
      NO_INSTRUCTION = 'NO_INSTRUCTION'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
