# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Indicates whether the transaction is eligible for seller protection. For
  # information, see [PayPal Seller Protection for
  # Merchants](https://www.paypal.com/us/webapps/mpp/security/seller-protection)
  # .
  class SellerProtectionStatus
    SELLER_PROTECTION_STATUS = [
      # TODO: Write general description for ELIGIBLE
      ELIGIBLE = 'ELIGIBLE'.freeze,

      # TODO: Write general description for PARTIALLY_ELIGIBLE
      PARTIALLY_ELIGIBLE = 'PARTIALLY_ELIGIBLE'.freeze,

      # TODO: Write general description for NOT_ELIGIBLE
      NOT_ELIGIBLE = 'NOT_ELIGIBLE'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
