# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Minimal representation of a cached setup token.
  class SetupTokenResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The PayPal-generated ID for the vault token.
    # @return [String]
    attr_accessor :id

    # Ordinal number for sorting.
    # @return [Integer]
    attr_accessor :ordinal

    # Customer in merchant's or partner's system of records.
    # @return [CustomerRequest]
    attr_accessor :customer

    # The status of the payment token.
    # @return [String]
    attr_accessor :status

    # The setup payment method details.
    # @return [SetupTokenResponsePaymentSource]
    attr_accessor :payment_source

    # An array of related [HATEOAS links](/api/rest/responses/#hateoas).
    # @return [Array[LinkDescription]]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['ordinal'] = 'ordinal'
      @_hash['customer'] = 'customer'
      @_hash['status'] = 'status'
      @_hash['payment_source'] = 'payment_source'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        ordinal
        customer
        status
        payment_source
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id: SKIP, ordinal: SKIP, customer: SKIP, status: 'CREATED',
                   payment_source: SKIP, links: SKIP)
      @id = id unless id == SKIP
      @ordinal = ordinal unless ordinal == SKIP
      @customer = customer unless customer == SKIP
      @status = status unless status == SKIP
      @payment_source = payment_source unless payment_source == SKIP
      @links = links unless links == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      ordinal = hash.key?('ordinal') ? hash['ordinal'] : SKIP
      customer = CustomerRequest.from_hash(hash['customer']) if hash['customer']
      status = hash['status'] ||= 'CREATED'
      payment_source = SetupTokenResponsePaymentSource.from_hash(hash['payment_source']) if
        hash['payment_source']
      # Parameter is an array, so we need to iterate through it
      links = nil
      unless hash['links'].nil?
        links = []
        hash['links'].each do |structure|
          links << (LinkDescription.from_hash(structure) if structure)
        end
      end

      links = SKIP unless hash.key?('links')

      # Create object from extracted values.
      SetupTokenResponse.new(id: id,
                             ordinal: ordinal,
                             customer: customer,
                             status: status,
                             payment_source: payment_source,
                             links: links)
    end
  end
end
