# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The location from which the shipping address is derived.
  class ShippingPreference
    SHIPPING_PREFERENCE = [
      # TODO: Write general description for GET_FROM_FILE
      GET_FROM_FILE = 'GET_FROM_FILE'.freeze,

      # TODO: Write general description for NO_SHIPPING
      NO_SHIPPING = 'NO_SHIPPING'.freeze,

      # TODO: Write general description for SET_PROVIDED_ADDRESS
      SET_PROVIDED_ADDRESS = 'SET_PROVIDED_ADDRESS'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
