# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # NACHA (the regulatory body governing the ACH network) requires that API
  # callers (merchants, partners) obtain the consumer’s explicit authorization
  # before initiating a transaction. To stay compliant, you’ll need to make sure
  # that you retain a compliant authorization for each transaction that you
  # originate to the ACH Network using this API. ACH transactions are
  # categorized (using SEC codes) by how you capture authorization from the
  # Receiver (the person whose bank account is being debited or credited).
  # PayPal supports the following SEC codes.
  class StandardEntryClassCode
    STANDARD_ENTRY_CLASS_CODE = [
      # TODO: Write general description for TEL
      TEL = 'TEL'.freeze,

      # TODO: Write general description for WEB
      WEB = 'WEB'.freeze,

      # TODO: Write general description for CCD
      CCD = 'CCD'.freeze,

      # TODO: Write general description for PPD
      PPD = 'PPD'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
