# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Indicates if this is a `first` or `subsequent` payment using a stored
  # payment source (also referred to as stored credential or card on file).
  class StoredPaymentSourceUsageType
    STORED_PAYMENT_SOURCE_USAGE_TYPE = [
      # TODO: Write general description for FIRST
      FIRST = 'FIRST'.freeze,

      # TODO: Write general description for SUBSEQUENT
      SUBSEQUENT = 'SUBSEQUENT'.freeze,

      # TODO: Write general description for DERIVED
      DERIVED = 'DERIVED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
