# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The customer's tax ID type.
  class TaxIdType
    TAX_ID_TYPE = [
      # TODO: Write general description for BR_CPF
      BR_CPF = 'BR_CPF'.freeze,

      # TODO: Write general description for BR_CNPJ
      BR_CNPJ = 'BR_CNPJ'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
