# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # The tokenization method that generated the ID.
  class TokenRequestType
    TOKEN_REQUEST_TYPE = [
      # TODO: Write general description for SETUP_TOKEN
      SETUP_TOKEN = 'SETUP_TOKEN'.freeze,

      # TODO: Write general description for BILLING_AGREEMENT
      BILLING_AGREEMENT = 'BILLING_AGREEMENT'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
