# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Base vaulting specification. The object can be extended for specific use
  # cases within each payment_source that supports vaulting.
  class VaultInstruction < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Defines how and when the payment source gets vaulted.
    # @return [StoreInVaultInstruction]
    attr_accessor :store_in_vault

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['store_in_vault'] = 'store_in_vault'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(store_in_vault:)
      @store_in_vault = store_in_vault
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      store_in_vault =
        hash.key?('store_in_vault') ? hash['store_in_vault'] : nil

      # Create object from extracted values.
      VaultInstruction.new(store_in_vault: store_in_vault)
    end
  end
end
