# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Customizes the buyer experience during the approval process for payment with
  # Venmo.<blockquote><strong>Note:</strong> Partners and Marketplaces might
  # configure <code>shipping_preference</code> during partner account setup,
  # which overrides the request values.</blockquote>
  class VenmoWalletExperienceContext < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The business name of the merchant. The pattern is defined by an external
    # party and supports Unicode.
    # @return [String]
    attr_accessor :brand_name

    # The location from which the shipping address is derived.
    # @return [ShippingPreference]
    attr_accessor :shipping_preference

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['brand_name'] = 'brand_name'
      @_hash['shipping_preference'] = 'shipping_preference'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        brand_name
        shipping_preference
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(brand_name: SKIP,
                   shipping_preference: ShippingPreference::GET_FROM_FILE)
      @brand_name = brand_name unless brand_name == SKIP
      @shipping_preference = shipping_preference unless shipping_preference == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      brand_name = hash.key?('brand_name') ? hash['brand_name'] : SKIP
      shipping_preference =
        hash['shipping_preference'] ||= ShippingPreference::GET_FROM_FILE

      # Create object from extracted values.
      VenmoWalletExperienceContext.new(brand_name: brand_name,
                                       shipping_preference: shipping_preference)
    end
  end
end
