# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
