# paypal_server_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PaypalServerSdk
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
